name: project
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  http: ^0.13.4
  email_validator: ^2.0.1

  pie_chart: ^5.3.2
  
  cupertino_icons: ^1.0.2
#  persian_datetime_picker: ^2.4.0
  encrypted_shared_preferences: ^3.0.0
  shared_preferences: ^2.0.15

  
  file_picker: ^4.5.1
  flutter_summernote: ^1.0.0
  bottom_navy_bar: ^6.0.0
  jalali_table_calendar: ^1.1.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BZar
      fonts:
        - asset: assets/fonts/b_zar.ttf
    - family: BNzanin
      fonts:
            - asset: assets/fonts/b_nazanin.TTF
    - family: lotus
      fonts:
            - asset: assets/fonts/lotus.ttf
    - family: BLotus
      fonts:
            - asset: assets/fonts/b_lotus.ttf
